language: groovy
jdk:
- openjdk6
before_script:
  # if we run on the same box as previous build, make sure target is clean
  - rm -rf target
script: ./grailsw refresh-dependencies --non-interactive
  && ./grailsw test-app --non-interactive
  && ./grailsw package-plugin --non-interactive
  && ./grailsw doc --pdf --non-interactive
  && if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_REPO_SLUG == 'grails-plugins/grails-cache-ehcache' ]]; then ./doc.sh && ./grailsw publish-plugin --no-scm --allow-overwrite --non-interactive ; else echo "Not on master branch, so not publishing"; fi
env:
  global:
  - GIT_NAME="Craig Andrews"
  - GIT_EMAIL="candrews@integralblue.com"
  # travis encrypt -a env.global 'GRAILS_CENTRAL_USERNAME=myusername'
  # travis encrypt -a env.global 'GRAILS_CENTRAL_PASSWORD=mypassword'
  # travis encrypt -a env.global 'GH_TOKEN=token' # get the token from https://github.com/settings/applications
  - secure: ms4k1Py1fEILvqY3LfDdRrgY9CiKegsUt3dw9gDeZ6Udw+rHJ5If3nu/ByXM8DB72fbp6MiFFxfEMDyeeA7UZyZO6jyBVxMAimZ2MJT2UCnKxKD1xfXQFWqZmHgEilxSuBtsEjWWM2cfQ8i3H7O0VAjprMNYJRmKbPhUn6cF8TI=
  - secure: Sd35PRqnUV9+WCCbG3bQw8XzFrJRPFxE1KHAkLXCn9u9Psl+A42Z49IvRahVuFS7roN4/0ae+gD/cAC4eX9fXxM7AEUuW4bxDbBlcvqw7oD4I0cYoVQaGIk6KfAhTienWzNmxaRtOlNwMVs3eZbTtQ4lT98NDp1rbU4Cpxh5CbU=
  - secure: wdFg+zi82axRsGkvWkMhTti7rqudo5ywETf9IMiXN23e4pr85k8xtu1LAdVrwFaLD+LRgvY1BbHVrIY2AnglJzbkyiVNbG4DfUXgwIx4aoAd5lYOLDe6SaQC/+TI2lBctkTHHpP33x/n4DYgMYjcGu5wLjAFx9ABGbOH9Gt+wNI=
